<a href="https://colab.research.google.com/github/bigbirdjones/laguardia_data_analytics/blob/main/NYC_Cooling_Tower_System_Inspection_Results_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: LOAD THE DATA

## Main Dataset

I'll load my main dataset via API in 3 segments, then concatinate to create a full DataFrame.

My Dataset are results from inspections conducted by the Department of Health & Mental Hygiene (DOHMH) on cooling towers for large HVAC installations around the city.

These violations are covered by Chapter 8 of Title 24 of the Rules of The City of New York. (24 RCNY)

In [1]:
import pandas as pd

In [2]:
URL = "https://data.cityofnewyork.us/resource/f9wb-g8mb.csv?$limit=50000"

df1 = pd.read_csv(URL)

/tmp/ipykernel_31261/2484009375.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(URL)

In [3]:
URL = "https://data.cityofnewyork.us/resource/f9wb-g8mb.csv?$limit=50000&$offset=50000"

df2 = pd.read_csv(URL)

In [4]:
URL = "https://data.cityofnewyork.us/resource/f9wb-g8mb.csv?$limit=22000&$offset=100000"

df3 = pd.read_csv(URL)

In [5]:
full_df = pd.concat([df1, df2, df3])
full_df

,bin,system_id,address,borough,zip_code,status,active_equip,inspection_date,violation_code,law_section,...,citation_text,summons_number,inspection_type,bbl,latitude,longitude,community_board,council_district,census_tract,nta_code
0,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8U,24 RCNY §8-05(f)(5),...,NaN,196816281.0,Non-Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
1,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8C,24 RCNY §8-04(a),...,Respondent is in violation of 24 RCNY 8-04(a)(...,881249959.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
2,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8D,24 RCNY §8-04(b),...,Compliance inspections must be completed by a ...,881249968.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
3,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8E,24 RCNY §8-04(c),...,"At the time of inspection, operational records...",NaN,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
4,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8L,24 RCNY §8-05(c)(3),...,"At the time of inspection, upon Inspector's re...",881249977.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,1089902,2000010015,10 E 15TH ST,Manhattan,10003,Active,2,2025-09-29T00:00:00.000,AH8L,24 RCNY §8-05(c)(3),...,"At the time of inspection, upon Inspector's re...",NaN,Cycle,1008420034,40.736511,-73.992725,105.0,2.0,5200.0,MN0501
21996,1089902,2000010015,10 E 15TH ST,Manhattan,10003,Active,2,2025-09-29T00:00:00.000,AH8C,24 RCNY §8-04(a),...,Respondent failed to provide records of all re...,NaN,Cycle,1008420034,40.736511,-73.992725,105.0,2.0,5200.0,MN0501
21997,3034563,2000002267,421 EMPIRE BLVD,Brooklyn,11225,Active,1,2025-09-29T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,3013100001,40.664106,-73.947763,309.0,35.0,33100.0,BK0901
21998,3062367,2000010961,238 BEDFORD AVE,Brooklyn,11249,Active,1,2025-09-29T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,3023510006,40.716083,-73.959612,301.0,34.0,55300.0,BK0102
21999,1090180,2000014459,217 W 57TH ST,Manhattan,10019,Active,3,2025-09-26T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,1010297502,40.765923,-73.980979,105.0,6.0,13700.0,MN0502

## Auxillary Dataset

Next i'll load my auxillary dataset, which after cleaning I will merge with the main dataset.

These records are derived from the Office of Administrative Trials & Hearings.

They have +20 Million records spanning over a decade, so I queried the records on NYC Open Data to get only the ones from the issuing agency i'm looking for, which is 'COOLING TOWERS - DOHMH', and downloaded the results in a csv.

In [6]:
URL2 = "/content/drive/MyDrive/NYC Cooling Tower EDA Capstone/OATH_Hearings_Division_Case_Status_20260409.csv"
oath_df = pd.read_csv(URL2)

/tmp/ipykernel_31261/2915690999.py:2: DtypeWarning: Columns (31,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  oath_df = pd.read_csv(URL2)

I'm dropping these columns immediately because they are obviously empty from even a cursory glance at the spreadsheet.

They are for charges 2 thru 10, but in the cases i'm looking at, the DOHMH seems to have only issued a single charge per ticketed violation, so it's one charge per row.

OATH handles administrative hearings for multiple city agencies, so it makes sense to leave space, but goodbye empty columns!

In [7]:
oath_df = oath_df.drop(oath_df.columns[[42,43,44,45,46,47,48,49,50,
                                        51,52,53,54,55,56,57,58,59,60,
                                        61,62,63,64,65,66,67,68,69,70,
                                        71,72,73,74,75,76,77]], axis=1)

(I know this is technically cleaning, but it's my notebook and I'll decide where the title breaks go... speaking of which)

#Step 2: CLEAN THE DATA

## Dropping NaN's

First, anyone who wasn't issued a violation I'm not interested in, so NaN's in the **'violation_code'** column are my first target.

In [8]:
full_df["violation_code"].isnull().sum()

np.int64(33807)

In [9]:
full_df.dropna(subset="violation_code", inplace= True)

In [10]:
print(122000-33795)

88205

Next, the **'summons_number'** is how I'm linking my main data set with the **'Ticket Number'** in the auxillary dataset, so NaN's there need to be dealt with as well.

In [11]:
full_df['summons_number'].isnull().sum()

np.int64(33750)

In [12]:
full_df.dropna(subset='summons_number', inplace= True)

In [13]:
print(88205-33761)

54444

Then a quick datatype recast from float64 to Int64 so the key columns will match.

In [14]:
# A quick datatype recast from float64 to Int64 so the key columns will match.

In [15]:
full_df['summons_number'] = full_df['summons_number'].astype(int)

In [16]:
full_df

,bin,system_id,address,borough,zip_code,status,active_equip,inspection_date,violation_code,law_section,...,citation_text,summons_number,inspection_type,bbl,latitude,longitude,community_board,council_district,census_tract,nta_code
0,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8U,24 RCNY §8-05(f)(5),...,NaN,196816281,Non-Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
1,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8C,24 RCNY §8-04(a),...,Respondent is in violation of 24 RCNY 8-04(a)(...,881249959,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
2,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8D,24 RCNY §8-04(b),...,Compliance inspections must be completed by a ...,881249968,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
4,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8L,24 RCNY §8-05(c)(3),...,"At the time of inspection, upon Inspector's re...",881249977,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
7,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8S,24 RCNY §8-05(f)(3),...,"At the time of inspection, records provided by...",881249986,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21947,1081661,2000000725,281 1ST AVE,Manhattan,10003,Active,1,2025-10-06T00:00:00.000,AH8R,24 RCNY §8-05(f)(2),...,"At the time of inspection, the on-site represe...",881327756,Cycle,1009220046,40.733328,-73.982345,NaN,NaN,4800.0,MN0602
21949,1081661,2000000725,281 1ST AVE,Manhattan,10003,Active,1,2025-10-06T00:00:00.000,AH8F,24 RCNY §8-04(d),...,The cooling tower system must be cleaned at le...,881327729,Cycle,1009220046,40.733328,-73.982345,NaN,NaN,4800.0,MN0602
21951,1081661,2000000725,281 1ST AVE,Manhattan,10003,Active,1,2025-10-06T00:00:00.000,AH8L,24 RCNY §8-05(c)(3),...,"At the time of inspection, the onsite represen...",881327738,Cycle,1009220046,40.733328,-73.982345,NaN,NaN,4800.0,MN0602
21953,1081661,2000000725,281 1ST AVE,Manhattan,10003,Active,1,2025-10-06T00:00:00.000,AH8Q,24 RCNY §8-05(f)(1),...,"At the time of inspection, operational records...",881327747,Cycle,1009220046,40.733328,-73.982345,NaN,NaN,4800.0,MN0602
21958,1083796,2000014331,636 11TH AVE,Manhattan,10036,Active,1,2025-10-03T00:00:00.000,AH8U,24 RCNY §8-05(f)(5),...,"At the time of inspection, operational records...",881327399,Cycle,1010750001,40.763676,-73.996220,104.0,3.0,12902.0,MN0402

In [17]:
oath_df

,Ticket Number,Violation Date,Violation Time,Issuing Agency,Respondent First Name,Respondent Last Name,Balance Due,Violation Location (Borough),Violation Location (Block No.),Violation Location (Lot No.),...,Respondent Address or Facility Number(For FDNY and DOB Tickets),Penalty Imposed,Paid Amount,Additional Penalties or Late Fees,Compliance Status,Violation Description,Charge #1: Code,Charge #1: Code Section,Charge #1: Code Description,Charge #1: Infraction Amount
0,193687506,NaN,10:30:00,COOLING TOWERS - DOHMH,NaN,EIB KEITREL LLC,$0.00,BROOKLYN,5320.0,24.0,...,NaN,$0.00,$0.00,$0.00,All Terms Met,NaN,AH7A,24RCNY31-02 A,FAIL TO SUBMIT REPORT OF PREVIOUS YEAR'S INSPE...,$250.00
1,193688193,NaN,10:30:00,COOLING TOWERS - DOHMH,NaN,919,$0.00,MANHATTAN,300.0,10.0,...,NaN,$0.00,$0.00,$0.00,All Terms Met,NaN,AH7A,24RCNY31-02 A,FAIL TO SUBMIT REPORT OF PREVIOUS YEAR'S INSPE...,$250.00
2,193662087,NaN,09:52:00,COOLING TOWERS - DOHMH,NaN,ST BARTHOLOMEWS CHURCH,$0.00,MANHATTAN,1305.0,1.0,...,NaN,$0.00,$0.00,$0.00,All Terms Met,NaN,AH8C,24RCNY8-04 A,"ROUTINE MONIT NOT CONDUCT,DOC'D AT LEAST ONCE ...",$500.00
3,193677267,NaN,10:30:00,COOLING TOWERS - DOHMH,NaN,55 LIBERTY OWNERS CORP,$0.00,MANHATTAN,64.0,8.0,...,NaN,$0.00,$0.00,$0.00,All Terms Met,NaN,AH7A,24RCNY31-02 A,FAIL TO SUBMIT REPORT OF PREVIOUS YEAR'S INSPE...,$250.00
4,193671812,NaN,09:54:00,COOLING TOWERS - DOHMH,NaN,ANDREW J TUNICK AS TRUSTEE,$0.00,MANHATTAN,867.0,1.0,...,NaN,$0.00,$0.00,$0.00,All Terms Met,NaN,AH8B,24RCNY8-03,MAINTENANCE PROGRAM AND PLAN INCOMPLETE OR NOT...,$500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58333,880698390,09/21/2015,13:34:00,COOLING TOWERS - DOHMH,NaN,STERLING LANDLORD CORP,$0.00,MANHATTAN,1022.0,35.0,...,NaN,"$2,000.00","$2,000.00",$0.00,All Terms Met,NaN,AH3K,NYCHC 3.05,"FAILING TO COMPLY WITH DEPT, BOARD OF HEALTH, ...","$1,000.00"
58334,880698345,09/21/2015,13:34:00,COOLING TOWERS - DOHMH,NaN,261 FIFTH AVENUE TIC,"$2,000.00",MANHATTAN,858.0,78.0,...,NaN,"$2,000.00",$0.00,$0.00,Penalty Due,NaN,AH3K,NYCHC 3.05,"FAILING TO COMPLY WITH DEPT, BOARD OF HEALTH, ...","$1,000.00"
58335,880698428,09/21/2015,13:34:00,COOLING TOWERS - DOHMH,NaN,WOODWARD AFFLILIATES,"$2,000.00",MANHATTAN,1026.0,41.0,...,NaN,"$2,000.00",$0.00,$0.00,Penalty Due,NaN,AH3K,NYCHC 3.05,"FAILING TO COMPLY WITH DEPT, BOARD OF HEALTH, ...","$1,000.00"
58336,880698868,09/21/2015,13:34:00,COOLING TOWERS - DOHMH,NaN,COLLEGE POINT HOLDINGS LLC,"$2,000.00",QUEENS,4172.0,7.0,...,NaN,"$2,000.00",$0.00,$0.00,Penalty Due,NaN,AH3K,NYCHC 3.05,"FAILING TO COMPLY WITH DEPT, BOARD OF HEALTH, ...","$1,000.00"
58337,880698776,09/21/2015,13:34:00,COOLING TOWERS - DOHMH,NaN,175 PEARL OWNER LLC,"$2,000.00",BROOKLYN,87.0,5.0,...,NaN,"$2,000.00",$0.00,$0.00,Penalty Due,NaN,AH3K,NYCHC 3.05,"FAILING TO COMPLY WITH DEPT, BOARD OF HEALTH, ...","$1,000.00"

## Merge DataFrames

In [18]:
combo_df = pd.merge(full_df, oath_df, left_on='summons_number', right_on='Ticket Number')

In [19]:
combo_df.columns

Index(['bin', 'system_id', 'address', 'borough', 'zip_code', 'status',
       'active_equip', 'inspection_date', 'violation_code', 'law_section',
       'violation_text', 'violation_type', 'citation_text', 'summons_number',
       'inspection_type', 'bbl', 'latitude', 'longitude', 'community_board',
       'council_district', 'census_tract', 'nta_code', 'Ticket Number',
       'Violation Date', 'Violation Time', 'Issuing Agency',
       'Respondent First Name', 'Respondent Last Name', 'Balance Due',
       'Violation Location (Borough)', 'Violation Location (Block No.)',
       'Violation Location (Lot No.)', 'Violation Location (House #)',
       'Violation Location (Street Name)', 'Violation Location (Floor)',
       'Violation Location (City)', 'Violation Location (Zip Code)',
       'Violation Location (State Name)', 'Respondent Address (Borough)',
       'Respondent Address (House #)', 'Respondent Address (Street Name)',
       'Respondent Address (City)', 'Respondent Address (Zip Code)',
       'Respondent Address (State Name)', 'Hearing Status', 'Hearing Result',
       'Scheduled Hearing Location', 'Hearing Date', 'Hearing Time',
       'Decision Location (Borough)', 'Decision Date',
       'Total Violation Amount', 'Violation Details', 'Date Judgment Docketed',
       'Respondent Address or Facility Number(For FDNY and DOB Tickets)',
       'Penalty Imposed', 'Paid Amount', 'Additional Penalties or Late Fees',
       'Compliance Status', 'Violation Description', 'Charge #1: Code',
       'Charge #1: Code Section', 'Charge #1: Code Description',
       'Charge #1: Infraction Amount'],
      dtype='object')

There's a lot of redundant info here, so lets make something a little cleaner.

In [20]:
# Making a new Dataframe to cut down on redundant info and get the layout I want.

violations_df = combo_df[['Ticket Number', 'system_id', 'address', 'borough', 'zip_code', 'status', 'inspection_date','inspection_type', 'bbl', 'latitude', 'longitude', 'Violation Date', 'violation_code', 'law_section', 'Charge #1: Code Description', 'Respondent Last Name', 'Penalty Imposed', 'Paid Amount', 'Additional Penalties or Late Fees', 'Compliance Status']]

In [21]:
violations_df.set_index('inspection_date')

,Ticket Number,system_id,address,borough,zip_code,status,inspection_type,bbl,latitude,longitude,Violation Date,violation_code,law_section,Charge #1: Code Description,Respondent Last Name,Penalty Imposed,Paid Amount,Additional Penalties or Late Fees,Compliance Status
inspection_date,,,,,,,,,,,,,,,,,,,
2021-05-21T00:00:00.000,196816281,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,Non-Cycle,1008330078,40.748260,-73.988491,05/21/2021,AH8U,24 RCNY §8-05(f)(5),REQUIRED CORRECTIVE ACTION NOT TAKEN BASED ON ...,THE JANE H GOLDMAN 2008Y-11,"$2,000.00","$2,204.00",$0.00,All Terms Met
2021-05-21T00:00:00.000,881249959,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,Cycle,1008330078,40.748260,-73.988491,05/21/2021,AH8C,24 RCNY §8-04(a),"ROUTINE MONIT NOT CONDUCT,DOC D AT LEAST ONCE ...",C O SOLIL MANAGEMENT LLC,$500.00,$500.00,$0.00,All Terms Met
2021-05-21T00:00:00.000,881249968,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,Cycle,1008330078,40.748260,-73.988491,05/21/2021,AH8D,24 RCNY §8-04(b),"COMPL INSPEC NOT CONDUCT,DOC D ONCE EVERY 90 D...",C O SOLIL MANAGEMENT LLC,$500.00,$500.00,$0.00,All Terms Met
2021-05-21T00:00:00.000,881249977,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,Cycle,1008330078,40.748260,-73.988491,05/21/2021,AH8L,24 RCNY §8-05(c)(3),NO RECORDS OF ALL CHEMICALS AND BIOCIDES ADDED...,C O SOLIL MANAGEMENT LLC,$0.00,$0.00,$0.00,All Terms Met
2021-05-21T00:00:00.000,881249986,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,Cycle,1008330078,40.748260,-73.988491,05/21/2021,AH8S,24 RCNY §8-05(f)(3),LEGIONELLA SAMP NOT COLLECT ANALYZE RESULTS NO...,C O SOLIL MANAGEMENT LLC,"$1,000.00","$1,000.00",$0.00,All Terms Met
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-06T00:00:00.000,881327756,2000000725,281 1ST AVE,Manhattan,10003,Active,Cycle,1009220046,40.733328,-73.982345,10/06/2025,AH8R,24 RCNY §8-05(f)(2),FAIL TO COLLECT ANALYZE RECORD WEEKLY BIO PROC...,BETH ISRAEL HOSPITAL,$500.00,$0.00,$0.00,Penalty Due
2025-10-06T00:00:00.000,881327729,2000000725,281 1ST AVE,Manhattan,10003,Active,Cycle,1009220046,40.733328,-73.982345,10/06/2025,AH8F,24 RCNY §8-04(d),TWICE YEARLY OR OTHER REQUIRED CLEANING NOT CO...,BETH ISRAEL HOSPITAL,$500.00,$0.00,$0.00,Penalty Due
2025-10-06T00:00:00.000,881327738,2000000725,281 1ST AVE,Manhattan,10003,Active,Cycle,1009220046,40.733328,-73.982345,10/06/2025,AH8L,24 RCNY §8-05(c)(3),NO RECORDS OF ALL CHEMICALS AND BIOCIDES ADDED...,BETH ISRAEL HOSPITAL,$500.00,$0.00,$0.00,Penalty Due
2025-10-06T00:00:00.000,881327747,2000000725,281 1ST AVE,Manhattan,10003,Active,Cycle,1009220046,40.733328,-73.982345,10/06/2025,AH8Q,24 RCNY §8-05(f)(1),MINIMUM DAILY WATER QUALITY MEASUREMENTS NOT T...,BETH ISRAEL HOSPITAL,$500.00,$0.00,$0.00,Penalty Due
2025-10-03T00:00:00.000,881327399,2000014331,636 11TH AVE,Manhattan,10036,Active,Cycle,1010750001,40.763676,-73.996220,10/03/2025,AH8U,24 RCNY §8-05(f)(5),REQUIRED CORRECTIVE ACTION NOT TAKEN BASED ON ...,PLAZA WEST ASSOCIATES LLC,"$1,000.00","$1,000.00",$0.00,All Terms Met

The court records list the fine amounts as strings, so i need to convert them to numeric to aggregate properly.

In [22]:
violations_df['Penalty Imposed'].unique()

array(['$2,000.00', '$500.00', '$0.00', '$1,000.00', '$530.00',
       '$1,030.00', '$250.00', '$300.00'], dtype=object)

In [23]:
violations_df['Penalty Imposed'] = violations_df['Penalty Imposed'].replace(
    {'$2,000.00': 2000,'$1,030.00': 1030, '$1,000.00': 1000, '$530.00': 530,
     '$500.00': 500, '$300.00': 300, '$250.00': 250, '$0.00': 0}
    )

/tmp/ipykernel_31261/3075260518.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  violations_df['Penalty Imposed'] = violations_df['Penalty Imposed'].replace(
/tmp/ipykernel_31261/3075260518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  violations_df['Penalty Imposed'] = violations_df['Penalty Imposed'].replace(

The variation in the 'Paid Amount' column is intriguing but a little more granular than I need right now.

I just want to see who has racked up the most fines, not who incurred the most late fees.

In [24]:
# Wish I could figure something out for this.

In [25]:
violations_df['Paid Amount'].unique()

array(['$2,204.00', '$500.00', '$0.00', '$1,000.00', '$625.00',
       '$1,250.00', '$1,076.00', '$2,000.00', '$1,030.00', '$2,060.00',
       '$530.00', '$750.00', '$3,500.00', '$1,015.00', '$2,154.00',
       '$400.00', '$520.00', '$1,065.00', '$833.00', '$1,500.00',
       '$600.00', '$1,050.00', '$542.00', '$1,042.00', '$166.00',
       '$2,135.00', '$1,028.00', '$1,039.00', '$1,054.00', '$916.00',
       '$1,020.00', '$2,020.00', '$800.00', '$499.00', '$840.00',
       '$2,097.00', '$2,098.00', '$497.00', '$715.00', '$710.00',
       '$60.00', '$700.00', '$1,053.00', '$1,079.00', '$2,079.00',
       '$1,600.00', '$50.00', '$177.00', '$2,018.00', '$300.00',
       '$1,033.00', '$2,107.00', '$730.00', '$1,087.00', '$2,030.00',
       '$2,087.00', '$100.00', '$250.00', '$200.00', '$470.00',
       '$1,125.00', '$525.00', '$2,620.00', '$2,731.00', '$982.00',
       '$2,024.00', '$2,073.00', '$25.00', '$180.00', '$551.00',
       '$2,358.00', '$1,179.00', '$2,405.00', '$1,170.00', '$3,000.00',
       '$450.00', '$2,313.00', '$394.00', '$2,067.00', '$-1,000.00',
       '$1,300.00', '$770.00', '$1,610.00', '$2,050.00', '$30.00',
       '$1,530.00', '$220.00', '$2,263.00', '$1,066.00', '$2,066.00',
       '$1,629.00', '$2,039.00', '$2,500.00', '$950.00', '$920.00',
       '$2,022.00', '$1,025.00', '$1,051.00', '$2,170.00', '$1,068.00',
       '$2,068.00', '$1,164.00', '$633.00', '$634.00', '$371.00',
       '$544.00', '$1,044.00', '$892.00', '$1,200.00', '$810.00',
       '$1,183.00', '$2,247.00', '$2,357.00', '$2,530.00', '$540.00',
       '$59.00', '$1,380.00', '$380.00', '$1,153.00', '$2,153.00',
       '$2,199.00', '$2,074.00', '$4,000.00', '$1,018.00', '$900.00',
       '$1,126.00', '$1,800.00', '$2,774.00', '$1,010.00', '$209.00',
       '$1,201.00', '$275.00', '$1,275.00', '$745.00', '$725.00',
       '$550.00', '$2,122.00', '$2,179.00', '$935.00', '$310.00',
       '$130.00', '$2,242.00', '$2,960.00', '$80.00', '$1,129.00',
       '$2,336.00', '$1,336.00', '$1,287.00', '$1,127.00', '$2,614.00',
       '$2,549.00', '$1,400.00', '$1,240.00', '$375.00', '$165.00',
       '$2,075.00', '$2,101.00', '$756.00', '$2,111.00', '$2,210.00',
       '$632.00', '$740.00', '$4,200.00', '$75.00', '$1,097.00',
       '$3,350.00', '$1,560.00', '$475.00'], dtype=object)

# Step 3: ANALYZE THE DATA

In [28]:
import seaborn as sns

In [27]:
violations_df.dtypes

Ticket Number                          int64
system_id                              int64
address                               object
borough                               object
zip_code                              object
status                                object
inspection_date                       object
inspection_type                       object
bbl                                    int64
latitude                             float64
longitude                            float64
Violation Date                        object
violation_code                        object
law_section                           object
Charge #1: Code Description           object
Respondent Last Name                  object
Penalty Imposed                        int64
Paid Amount                           object
Additional Penalties or Late Fees     object
Compliance Status                     object
dtype: object

In [29]:
total_penalty_imposed = violations_df.groupby(['Respondent Last Name'])['Penalty Imposed'].sum()

top_offenders = total_penalty_imposed.sort_values(ascending=False).head(20)

In [30]:
penalty_per_building = violations_df.groupby(['Respondent Last Name', 'address'])['Penalty Imposed'].sum()

top_offending_buildings = penalty_per_building.sort_values(ascending=False).head(20)

In [31]:
penalty_per_type = violations_df.groupby(['Respondent Last Name', 'violation_code'])['Penalty Imposed'].sum()

top_violation_types = penalty_per_type.sort_values(ascending=False).head(30)

In [33]:
top_offenders

Respondent Last Name
OWNER AGENT IN CHARGE OF COOLI    173920
NEW YORK UNIVERSITY               149720
TIFFANY REALTY CO LLC              80000
OWNER OF                           66060
JAMESTOWN MANAGEMENT               64000
ANDREWS BUILDING CORP              58000
225 BROADWAY COMPANY               58000
LLC                                49650
TONG FAT REALTY CORP               47300
LONG ISLAND UNIVERSITY             46420
SL GREEN REALTY                    44030
PROMENADE CONDO                    44000
PARKCHESTER SOUTH CONDOMINIUM      43250
VORNADO LF 50 WEST 57TH STREET     42500
D-AHN DEVELOPMENTS LLC             41000
675 OWNERSHIP LLC                  40000
ESRT 501 SEVENTH AVENUE L L C      39500
DIAZ                               39000
RICHMOND MEDICAL CENTER            37500
THE GREENPOINT SAVINGS BANK        37000
Name: Penalty Imposed, dtype: int64

In [34]:
top_offending_buildings

Respondent Last Name            address
TIFFANY REALTY CO LLC           130 HAVEMEYER ST           80000
JAMESTOWN MANAGEMENT            75 9TH AVE                 64000
225 BROADWAY COMPANY            225 BROADWAY               58000
PROMENADE CONDO                 89 JOHN STREET             44000
SL GREEN REALTY                 16 COURT ST                43000
VORNADO LF 50 WEST 57TH STREET  50 W 57TH ST               42500
D-AHN DEVELOPMENTS LLC          25-22 ASTORIA BLVD         41000
675 OWNERSHIP LLC               675 6TH AVE                40000
ESRT 501 SEVENTH AVENUE L L C   501 7TH AVE                39500
RICHMOND MEDICAL CENTER         355 BARD AVE               37500
TRUMP PLACE CONDOMINIUM C O     1175 3 AVENUE              36000
NBA HOLDINGS                    30-15 48TH AVENUE          35500
NEW YORK UNIVERSITY             6 METROTECH                35030
UNITED TALMUDICAL ACADEMY       5411 FORT HAMILTON PKWY    35000
THE 180 LIVINGSTON STREET COND  180 LIVINGSTON ST          34500
130 COURT LLC                   130 COURT ST               34500
RUDIN MGMT CO INC               32 6TH AVE                 34500
ANDREWS BUILDING CORP           117 W 17TH ST              34000
JORALEMON ASSOCIATES            186 JORALEMON ST           33000
C O UNITED AMERICAN LAND LLC    210 JORALEMON ST           32000
Name: Penalty Imposed, dtype: int64

In [38]:
top_violation_types

Respondent Last Name            violation_code
OWNER AGENT IN CHARGE OF COOLI  AH8S              52000
NEW YORK UNIVERSITY             AH8S              49150
                                AH8C              26150
OWNER AGENT IN CHARGE OF COOLI  AH8C              20060
NEW YORK UNIVERSITY             AH8L              19620
OWNER AGENT IN CHARGE OF COOLI  AH8R              18090
PROMENADE CONDO                 AH8S              16000
TIFFANY REALTY CO LLC           AH8S              16000
OWNER AGENT IN CHARGE OF COOLI  AH8L              14590
TIFFANY REALTY CO LLC           AH8A              14000
OWNER AGENT IN CHARGE OF COOLI  AH8U              13000
                                AH8Q              12030
ANDREWS BUILDING CORP           AH8S              12000
OWNER OF                        AH8S              12000
NEW YORK UNIVERSITY             AH8R              11090
OWNER AGENT IN CHARGE OF COOLI  AH8F              10560
NEW YORK UNIVERSITY             AH8U              10090
LONG ISLAND UNIVERSITY          AH8S              10030
OWNER AGENT IN CHARGE OF COOLI  AH8D              10030
RUDIN MGMT CO INC               AH8S              10000
JAMESTOWN MANAGEMENT            AH8S               9500
TONG FAT REALTY CORP            AH8S               9030
SILVER AUTUMN HTL CORP          AH8S               9000
675 OWNERSHIP LLC               AH8S               9000
225 BROADWAY COMPANY            AH8S               9000
JAMESTOWN MANAGEMENT            AH8C               9000
32 SIXTH AVENUE CO LLC          AH8S               9000
THE 180 LIVINGSTON STREET COND  AH8S               9000
BROOKLYN UNION GAS COMPANY      AH8S               8060
NEW YORK UNIVERSITY             AH8D               8030
Name: Penalty Imposed, dtype: int64